language: node_js
node_js:
  - "8"
script:
  - npm run lint
  - npm run-script test-travis
after_success:
  # Send coverage data to Coveralls
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
