name: CI

on:
  pull_request:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: Run Lint
        uses: stefanoeb/eslint-action@1.0.0
      - name: npm test
        run: npm test
        env:
          CI: true

  publishnpm:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.npm_token }}

      - if: jobs.publishnpm.steps.publish.type != 'none'
        run: |
          echo "Version changed: ${{ jobs.publishnpm.steps.publish.old-version }} => ${{ jobs.publishnpm.steps.publish.version }}"
      - if: jobs.publishnpm.steps.publish.type == 'none'
        name: npm next release
        uses: epeli/npm-release@v1
        with:
          type: prerelease
          token: ${{ secrets.npm_token }}
