name: CI

on:
  pull_request:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: Run Lint
        uses: stefanoeb/eslint-action@1.0.0
      - name: npm test
        run: npm test
        env:
          CI: true

  publish-npm:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

  release-please:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v1.6.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: node-red-contrib-home-assistant-websocket
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        if: ${{ steps.release.outputs.release_created }}
      - name: npm next release
        uses: epeli/npm-release@v1
        with:
          type: prerelease
          token: ${{ secrets.npm_token }}
        if: ${{ !steps.release.outputs.release_created }}
