name: CI

on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: Run Lint
        uses: stefanoeb/eslint-action@1.0.0
      - name: npm test
        run: npm test
        env:
          CI: true

  publish-npm:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: "Type: prerelease"
        run: echo "::set-env name=RELEASE_TYPE::prerelease"
      - name: "Type: release"
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "::set-env name=RELEASE_TYPE::release"
      - uses: actions/checkout@v1
      - name: npm release
        uses: epeli/npm-release@v1
        with:
          type: ${{ env.RELEASE_TYPE }}
          token: ${{ secrets.npm_token }}
