name: Convert Documentation

on:
  push:
    branches: dev
    paths:
      - "docs/**/*.md"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - name: Convert Docs
        run: npm run docs:convert
      - uses: zachowj/git-auto-commit-action@master
        with:
          commit_message: "docs: Convert markdown docs to Node-RED help files"
          branch: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
