name: Convert Documentation

on:
  push:
    branches: dev
    paths:
      - "docs/**/*.md"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - name: Convert Docs
        run: npm run docs:Convert
      - uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Convert markdown docs to Node-RED help files
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
