name: Format Docs (prettier)

on:
  pull_request:
    paths:
      - "docs/**/*.md"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - name: Run prettier
        run: npm run docs:lint
      - uses: zachowj/git-auto-commit-action@master
        with:
          commit_message: "docs: Apply prettier changes for docs"
          branch: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
